- api/pom.xml
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>
> Changed groupId and artifactId (master)

- api/pom.xml
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>
> Changed groupId and artifactId (EE4J)

- api/pom.xml
- impl/pom.xml
- pom.xml
Updated parent pom version from 1.0.1 to 1.0.2
> Update parent pom version

- api/pom.xml
Signed-off-by: Mark Thomas <markt@apache.org>
> Restore correct value for extensionName

- api/pom.xml
- impl/pom.xml
- pom.xml
Apply various updates from master to EE4J_8 in preparation for the first release.
> Merge from master

- .gitignore
Signed-off-by: Mark Thomas <markt@apache.org>
> Copy .gitignore from master

- api/pom.xml
- impl/pom.xml
- pom.xml
Update the license header on all the files that have been modified since the initial import. (Only the POMs so far for this branch.)
> All of these files have been modified since the initial contribution.

- api/pom.xml
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
> Set API version to 3.0.1

- api/pom.xml
Nothing urgent. Update the parent pom and additional changes to align this version with EE4J_8 and keep the diff to a minimum.
> Align with EE4J_8

- api/pom.xml
- impl/pom.xml
- pom.xml
> Impl to 3.0.2 as well and added LICENSE/NOTICE to archive

- impl/pom.xml
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
> impl/pom.xml fix for RI release

- impl/pom.xml
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
> impl/pom.xml groupId fix for release

- pom.xml
> Set javadoc source level explicitly.

- api/pom.xml
- impl/pom.xml
- impl/src/main/java/com/sun/el/lang/ELArithmetic.java
- impl/src/main/java/com/sun/el/lang/ELSupport.java
- impl/src/main/java/com/sun/el/lang/EvaluationContext.java
- impl/src/main/java/com/sun/el/lang/ExpressionBuilder.java
- impl/src/main/java/com/sun/el/parser/AstFunction.java
- impl/src/main/java/com/sun/el/parser/ELParser.java
> #87 Additional updates to Jakarta Expression Language

- README.md
- api/pom.xml
> #87 Updated description and readme

- api/pom.xml
- impl/pom.xml
- pom.xml
> Prepare for 3.0.3 release

- api/src/main/java/javax/el/ELContext.java
- api/src/main/java/javax/el/StandardELContext.java
> Revert adding generic parameters - doesn't pass signature test

- api/pom.xml
- impl/pom.xml
- pom.xml
> Update bundle version to 3.0.3 as well

- api/src/main/java/javax/el/ELProcessor.java
Signed-off-by: Scott Marlow <smarlow@redhat.com>
I happened to notice this minor typo today.
> fix minor typo, change 'singnature' to 'signature'

- spec/src/main/asciidoc/license-efsl.adoc
- spec/src/main/asciidoc/scope.adoc
> Updated spec for latest Jakarta EE 8 requirements

- api/pom.xml
- api/src/main/javadoc/doc-files/speclicense.html
> Update Javadoc for latest Jakarta EE 8 requirements

- spec/src/main/asciidoc/expression-language-spec.adoc
> Updated doctitle to contain only spec name

- spec/pom.xml
> Spec version to 3.0

- pom.xml
> Merge release branch for 3.0.3

- api/src/main/java/javax/el/LambdaExpression.java
Signed-off-by: Scott Marlow <smarlow@redhat.com>
Apply fix for  [JBEE-158](https://issues.jboss.org/browse/JBEE-158)
> ensure that we always exitLambdaScope()

- spec/src/main/asciidoc/ELSpec.adoc
First pass at updating the spec doc
Still need to proof-read, fix cross-references and check against original 3.0 spec doc
> Spec updates

- pom.xml
> Prepare for RC1 combined release

- pom.xml
This reverts commit 0d19b582185d91d20138c9aa66f8b66e762a0c8b.
> Revert "Prepare for RC1 combined release"

- api/pom.xml
- combined-pom/pom.xml
- impl/pom.xml
- pom.xml
- spec/pom.xml
> Update versions and automatic module in pom, plus tidying

- spec/pom.xml
Signed-off-by: Jean-Louis Monteiro <jlmonteiro@tomitribe.com>
> Add jakarta- prefix to spec file names

- api/pom.xml
- impl/pom.xml
- pom.xml
Administrative only: complete last item of https://github.com/eclipse-ee4j/el-ri/issues/143
> Merge 4.0.0 into master

- api/pom.xml
- impl/pom.xml
> Set impl and api to snapshot

- impl/build.xml
- impl/src/main/java/com/sun/el/parser/ELParser.java
Fixes #136 - ELParser PermGen Memory Leak
> Fix #136 - ELParser PermGen Memory Leak

- impl/src/main/java/com/sun/el/parser/ELParser.jjt
- impl/src/main/java/com/sun/el/parser/ELParserTokenManager.java
- src/test/java/org/glassfish/el/test/EscapingTest.java
Contains copyright fixes of the previous https://github.com/eclipse-ee4j/el-ri/pull/160
> Fix copyrights

- api/pom.xml
- impl/pom.xml
- pom.xml
- spec/pom.xml
> Update dependency versions and copyright in poms

- impl/src/main/java/com/sun/el/lang/ExpressionBuilder.java
https://github.com/eclipse-ee4j/el-ri/issues/178
Signed-off-by: Clara Fang <clara.fang@gmail.com>
> Replace Usage of getParameterTypes().length with getParameterCount() #178

- api/src/main/java/jakarta/el/ArrayELResolver.java
- api/src/main/java/jakarta/el/BeanELResolver.java
- api/src/main/java/jakarta/el/BeanNameELResolver.java
- api/src/main/java/jakarta/el/CompositeELResolver.java
- api/src/main/java/jakarta/el/ELResolver.java
- api/src/main/java/jakarta/el/ListELResolver.java
- api/src/main/java/jakarta/el/MapELResolver.java
- api/src/main/java/jakarta/el/ResourceBundleELResolver.java
- api/src/main/java/jakarta/el/StaticFieldELResolver.java
- api/src/main/java/jakarta/el/TypeConverter.java
This is the first part of the fix for #47
> Remove deprecated getFeatureDescriptors() method

- api/src/main/java/jakarta/el/FactoryFinder.java
- spec/src/main/asciidoc/ELSpec.adoc
I plan to leave this open for a week or so before merging in case there are references I have missed or there is any other feedback.
> Fix #192 - remove all references to SecurityManager

- api/src/main/java/jakarta/el/BeanELResolver.java
- spec/src/main/asciidoc/ELSpec.adoc
Add change log entries, expand Javadoc and expand specification text
> Documentation updates for past changes

- api/pom.xml
- api/src/main/java/jakarta/el/RecordELResolver.java
- api/src/main/java/jakarta/el/StandardELContext.java
- spec/src/main/asciidoc/ELSpec.adoc
Note this also increases the JRE minimum to 17.
> Fix #201 add support for Record

- api/src/main/java/jakarta/el/ArrayELResolver.java
Also update the Javadoc to better described the behaviour for the length property and to fix a copy/paste issue.
> Fix TCK failures when testing 'length' as a read-only property

- spec/pom.xml
- spec/src/main/asciidoc/ELSpec.adoc
- spec/src/main/asciidoc/expression-language-spec.adoc
- spec/src/main/asciidoc/license-efsl.adoc
Lots of minor proof-reading fixes getting ready for 6.0 release
> Spec proof reading

- pom.xml
As advised by Eclipse Helpdesk
> Add config for publishing to Maven Central

- api/pom.xml
- pom.xml
> Publish central
